apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: badada-backend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/badada-backend
  newTag: cfbda6063c516d829c20cfd8d64890a3a1bc522e
