apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: badada-backend-image
  newName: 270112669095.dkr.ecr.ap-northeast-2.amazonaws.com/badada-backend
  newTag: 2373a8428b26b9157f1cfdfcf35a893215e3d162
